<!--
 * @Author: lu
 * @Date: 2020-10-14 09:43:55
 * @LastEditTime: 2020-10-14 09:49:02
 * @FilePath: \GSG-ES6-ES11\53_Promise.allSettled.html
 * @Description: 
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>53_Promise.allSettled</title>
</head>

<body>
    <script>
        // 声明两个promise对象
        const p1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('商品数据-1')
            }, 1000)
        });

        const p2 = new Promise((resolve, reject) => {
            setTimeout(() => {
                // resolve('商品数据-2')
                reject('出错了')
            }, 1000)
        });

        // 调用 allSettled 方法
        const result = Promise.allSettled([p1, p2]);
        console.log(result);    // 始终返回成功，0: {status: "fulfilled", value: "商品数据-1"}1: {status: "rejected", reason: "出错了"}

        const res = Promise.all([p1, p2]);
        console.log(res);   // 只要有一个失败就会返回失败，返回的值是失败promise的结果值
    </script>
</body>

</html>